logLevel = "DEBUG"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/api.example.com.crt"
      KeyFile = "/ssl/api.example.com.key"

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "api.example.com"
watch = true
